[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
cmds = ["npm ci --no-audit --no-fund || npm install --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
