[phases.setup]
nixPkgs = ["nodejs", "ffmpeg"]

[phases.install]
cmds = ["npm ci --no-audit --no-fund --legacy-peer-deps || npm install --no-audit --no-fund --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
